### PR TITLE
style: Main screen layout modified

### PR DESCRIPTION
**Pull request by shantanu0323**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [✓] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [✓] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by mayank-kgp** [comment]
@shantanu0323 Please squash 2 commits into 1. Rest looks good.

**Comment by shantanu0323** [comment]
@mayank-kgp I have squashed the 2 commits into 1. You can now merge the pull request if no further modifications are necessary. :coffee:

**Comment by shantanu0323** [comment]
@mayank-kgp I have squashed the 2 commits into 1. You can now merge the pull request if no further modifications are necessary. :coffee:

**Comment by mayank-kgp** [comment]
@shantanu0323 Please remove the jargon from commit message and write a proper commit message. You can see the commit message of other merged PR.

**Comment by shantanu0323** [comment]
@mayank-kgp Is the commit msg ok now?

**Comment by mayank-kgp** [comment]
Yes

**Review by mayank-kgp — APPROVED** [review]

**Pull request merged**
