### PR TITLE
Solves Issues #15 and #21

### PR DESCRIPTION
**Pull request by AK-007**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by mayank-kgp** [comment]
@AK-007 1 PR should address only one issue.

**Comment by mayank-kgp** [comment]
@AK-007 Please let me know the status. You need to send different PR for each issue.

**Comment by AK-007** [comment]
I changed the code for both the issues...how should I send the 2nd PR?

**Comment by mayank-kgp** [comment]
@AK-007 This PR should contain code of only one issue. You should open new PR which contain code of another issue.

**Comment by AK-007** [comment]
@mayank-kgp Actually removing the Splash screen code automatically solves the Wrong App Name issue.
Hence one issue solves the other also....there is no need of extra code.....that is the reason of 1 PR.....

**Comment by AK-007** [comment]
@mayank-kgp plz review

**Comment by mayank-kgp** [comment]
@AK-007 Please see this - 
https://gitter.im/VoiceCalculator/discussion?at=5a26b7c5c65707ba2b154bad

**Pull request closed without merging**
