### PR TITLE
Landscape Layout Problem Resolved

### PR DESCRIPTION
**Pull request by RavneetDTU**
New Layout File added for Landscape View with same Button IDs, Name ,etc.
screenshot_20171201-014304

### CODE REVIEW

**Comment by mayank-kgp** [comment]
@RavneetDTU Please follow the commit style guides. https://github.com/mayank-kgp/VoiceCalculator/wiki/Commit-Style-Guide
You can write your commit message like - feat: landscape mode

**Comment by RavneetDTU** [comment]
@mayank-kgp ok , I will take care of this........
Do I need to send this Again??

**Comment by mayank-kgp** [comment]
@RavneetDTU Please amend the commit message and send again.

**Comment by RavneetDTU** [comment]
@mayank-kgp tried to write new Commit Message ....plz check

**Comment by mayank-kgp** [comment]
@RavneetDTU You made a new commit. You should have changed previous commit message.
Now there are 2 commits in this PR. It should have been only 1.

**Comment by mayank-kgp** [comment]
@RavneetDTU Are you working on it?

**Comment by RavneetDTU** [comment]
@mayank-kgp ,Yes I am Working on it.....I already sent PR According to older UI.....I am waiting for new Layouts to be Implemented .

**Comment by mayank-kgp** [comment]
@RavneetDTU Your code crashes the app on rotating the layout. Please test your code before sending the PR.

**Pull request merged**
